

server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkikg/github-springboot-cloudconfig-tolls
          username: 
          password: 
          search-paths:
          - 'station*'
          
         # repos:
          #  perf:
          #    pattern:
         #     - "/perf*"
        #    uri: https://github.com/venkikg/github-springboot-cloudconfig-tolls-perf
        #    search-paths:
        #      pattern:
        #      - 'station*'
  security:
    user:
      name: test
      password: test       
            
